### ISSUE TITLE
Request: explain what this "analog loopback" does in the README

### ISSUE THREAD

**Issue by DeflateAwning** [TinyTapeout/tt06-analog-loopback#1]

**Comment by mattvenn** [comment]
this isn't clear enough? https://github.com/TinyTapeout/tt06-analog-loopback/blob/main/docs/info.md

**Comment by DeflateAwning** [comment]
I'm still learning, so maybe I'm not the target audience. Here's my feedback though:

1. I'd expect this info in the README, especially given how short it is. If not in the README, I'd expect the README to start with a link to that document.
2. Even after reading that, I still don't really understand what this is, what somewhat would use it for, why someone would want it, etc.
3. What are the "pairs" of analog pins? Perhaps a link to the relevant documentation would be helpful.

My guess is the following:

> This analog loopback design is a debugging/"control" design allows us to characterize the resistance and step response of the chip after manufacturing. This characterization is useful for calibrating the rest of the analog designs on this chip.

**Comment by mattvenn** [comment]
thanks, added your guess to the README!
